# Decision Tree Classification

In [ ]:
# Importing Files
from google.colab import files
uploaded= files.upload()

Saving Cleaned-Data.csv to Cleaned-Data.csv


## Importing the libraries

In [ ]:
import numpy as np #numerical data
import matplotlib.pyplot as plt
import pandas as pd #tabular data

## Importing the dataset

In [ ]:
dataset = pd.read_csv('Cleaned-Data.csv')
X = dataset.iloc[:,0:10].values
y = dataset.iloc[:,20].values

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[0 1 1 ... 1 1 0]
 [0 1 1 ... 0 0 0]
 [0 1 0 ... 0 1 0]
 ...
 [1 1 1 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]]


In [ ]:
print(y_train)

[0 0 1 ... 1 0 1]


In [ ]:
print(X_test)

[[1 1 1 ... 1 1 1]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 0]
 ...
 [1 1 1 ... 1 1 1]
 [0 1 1 ... 0 1 0]
 [1 1 1 ... 0 1 1]]


In [ ]:
print(y_test)

[1 0 1 ... 0 0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.67547469  1.00001684  0.88332064 ...  0.91166287  0.9137158
  -0.756534  ]
 [-0.67547469  1.00001684  0.88332064 ... -1.0968967  -1.09443221
  -0.756534  ]
 [-0.67547469  1.00001684 -1.13209174 ... -1.0968967   0.9137158
  -0.756534  ]
 ...
 [ 1.48044038  1.00001684  0.88332064 ... -1.0968967  -1.09443221
   1.32181766]
 [-0.67547469 -0.99998317 -1.13209174 ...  0.91166287 -1.09443221
  -0.756534  ]
 [-0.67547469 -0.99998317  0.88332064 ... -1.0968967  -1.09443221
  -0.756534  ]]


In [ ]:
print(X_test)

[[ 1.48044038  1.00001684  0.88332064 ...  0.91166287  0.9137158
   1.32181766]
 [-0.67547469 -0.99998317 -1.13209174 ...  0.91166287  0.9137158
   1.32181766]
 [-0.67547469 -0.99998317 -1.13209174 ...  0.91166287 -1.09443221
  -0.756534  ]
 ...
 [ 1.48044038  1.00001684  0.88332064 ...  0.91166287  0.9137158
   1.32181766]
 [-0.67547469  1.00001684  0.88332064 ... -1.0968967   0.9137158
  -0.756534  ]
 [ 1.48044038  1.00001684  0.88332064 ... -1.0968967   0.9137158
   1.32181766]]


## Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)
print(y_pred)

[0 0 0 ... 0 0 0]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[52948     0]
 [26252     0]]


0.6685353535353535