In [ ]:
from google.colab import files
uploaded= files.upload()

Saving Cleaned-Data.csv to Cleaned-Data.csv


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
 

In [ ]:
a = pd.read_csv('Cleaned-Data.csv')
print(a.head(10))
X = a.iloc[:,0:10].values          # 10 Symptoms 
Y = a.iloc[:,20].values            # Severity- severe

   Fever  Tiredness  Dry-Cough  ...  Contact_No  Contact_Yes  Country
0      1          1          1  ...           0            1    China
1      1          1          1  ...           1            0    China
2      1          1          1  ...           0            0    China
3      1          1          1  ...           0            1    China
4      1          1          1  ...           1            0    China
5      1          1          1  ...           0            0    China
6      1          1          1  ...           0            1    China
7      1          1          1  ...           1            0    China
8      1          1          1  ...           0            0    China
9      1          1          1  ...           0            1    China

[10 rows x 24 columns]


In [ ]:
# Training the model on the training dataset
from sklearn.model_selection import train_test_split   #dividing the data  
X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,random_state=1) # 70% trainig data
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

[[0 1 1 ... 1 1 1]
 [0 1 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
[[1 1 1 ... 1 1 0]
 [0 0 1 ... 1 1 0]
 [0 0 1 ... 1 1 1]
 ...
 [0 1 1 ... 0 1 1]
 [0 1 0 ... 1 0 0]
 [0 0 1 ... 0 1 1]]
[0 1 0 ... 0 0 0]
[1 0 1 ... 1 1 0]


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [ ]:
# fit function is used to train the model using the training sets as parameters
L=model.fit(X,Y)
print(L.coef_)
print(L.intercept_)                

[[ 8.81940325e-06 -6.52479491e-05  6.50410901e-05 -6.52479491e-05
   8.81940325e-06 -4.83742206e-05  5.91460258e-06  4.56696618e-06
   4.56696618e-06  5.91460257e-06]]
[-0.69314187]


In [ ]:
# performing predictions on the test dataset
prediction =model.predict(X_test) 
print(prediction)                      

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,prediction)                               

array([[63320,     0],
       [31720,     0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,prediction)

0.6662457912457912